### PR TITLE
fix: semantic-release setup

### PR DESCRIPTION
**Pull request by gr2m**
I _think_ this should fix the semantic-release setup. I had some problems when I was testing it with my fork. I use pretty much the same setup in many of my actions, I'm confused why this caused errors in the first place. Maybe because I ran it on a fork?

### CODE REVIEW

**Comment by gr2m** [comment]
I'm just going to merge it in to see if that fixes the release setup. 

If it doesn't, I'll debug this in a separate repository until I figure out what's up :)

**Comment by gr2m** [comment]
@stefanbuck I've no idea what this error means 😞 

image

I'll check in with GitHub support. For the time being I'll fix the `v1` branch manually so that we can continue to use the action :D

**Comment by stefanbuck** [comment]
I think it is caused by this line which ends with a double quotation mark, but there is no counter part. 

https://github.com/stefanbuck/github-issue-parser/blob/4bf510277d6e48f70e754757122339f11f314df8/.github/workflows/release.yml#L26

**Comment by gr2m** [comment]
That was it 👍🏼 Great catch!

**Pull request merged**
