### PR TITLE
fix: do not lowercase values

### LINKED ISSUE #1: Values are all lowercased
Hi Stefan!

I use your action for my automation at https://github.com/gr2m/helpdesk and made another show about it: https://github.com/gr2m/helpdesk/issues/42

One problem I realized is that all values seem to be lowercased. Is that intentional?

### PR DESCRIPTION
**Pull request by gr2m**
I updated the e2e test to support `E2E_USER_2FA` so that I could test with my 2FA enabled test user account. That worked, but the test never completed, and I'm not sure why. So I coudln't verify that the test actually passed locally on my machine. But I did update the snapshots and test manually according with the issue.

closes #1

### CODE REVIEW

**Review by stefanbuck — APPROVED** [review]
I'm glad that you figured out the testing part. I forgot to mention that the current test setup is a bit clunky. This is my first GitHub Action and since the underlying feature is still in beta, I thought it's a good idea to use a End 2 End test setup. The original idea was to use a user/password auth (a test user without 2fa enabled), but this didn't worked on CI because it was asking for a device authentication code during the CI run. Therefore I wonder how your setup is supposed to work, given it needs a 2fa code at runtime so to say. I guess a backup code could work, but only once, right? 

Anway, thanks for the contribution and the change looks good to me.

**Comment by gr2m** [comment]
> Therefore I wonder how your setup is supposed to work, given it needs a 2fa code at runtime so to say

I don't think a GitHub login would ever work on CI. But you could run it locally. Maybe add a simple e2e test to test the whole stack, but create integration tests for the rest

**Comment by stefanbuck** [comment]
> I don't think a GitHub login would ever work on CI. But you could run it locally. Maybe add a simple e2e test to test the whole stack, but create integration tests for the rest

Ahhh I see, I thought you made to 2FA login work on CI and I couldn't figure it out how. Right now I do run the tests locally with my test account (without 2fa), so thanks for this awesome contribution. As said, the test setup needs some further thinking but I'm quite busy with another GitHub related project ... https://jumpcat.dev (a command palette for GitHub)

**Comment by gr2m** [comment]
could you merge this fix in for the time being?

**Comment by stefanbuck** [comment]
You're welcome 🙂

**Pull request merged**
