### PR TITLE
Revert "Using env.runner_temp instead of home directory to write json file"

### PR DESCRIPTION
**Pull request by jamacku**
Reverts stefanbuck/github-issue-parser#59

Follow-up to:
- https://github.com/stefanbuck/github-issue-parser/pull/75

Please see:
- https://github.com/stefanbuck/github-issue-parser/issues/74
- https://github.com/stefanbuck/github-issue-parser/commit/7296f0807778ed0f15b3625461fd61179a40e583#commitcomment-142592610

/cc @gr2m @joshjohanning

### CODE REVIEW

**Comment by jamacku** [comment]
I think that the original revert doesn't revert the breaking change introduced in:

https://github.com/stefanbuck/github-issue-parser/pull/59/files#diff-e727e4bdf3657fd1d798edcd6b099d6e092f8573cba266154583a746bba0f346

@FlafyDev This might break your setup again. 😢 Sorry about that. But It will unblock all users who access JSON file directly and haven't noticed yet.

**Comment by FlafyDev** [comment]
> This might break your setup again. 😢 Sorry about that. But It will unblock all users who access JSON file directly and haven't noticed yet.

yeah that's fine lol. that comment was mostly a joke
i'll subscribe to this PR to know when to update my thing

**Review by gr2m — APPROVED** [review]
sorry no idea what happened in #75, it's been a long day ...

**Comment by jamacku** [comment]
> sorry no idea what happened in #75, it's been a long day ...

No problem :)

I see that the semantic-release action [failed](https://github.com/stefanbuck/github-issue-parser/actions/runs/9328160136/job/25678996429#step:8:50) :/

```
[6:12:00 AM] [semantic-release] › ✘  An error occurred while running semantic-release: ExecaError: Command failed with exit code 128: git tag v3.2.1 c9e47737b81057fcdcbf95d412a34aafb0e4ed00
```

Not sure what happened there. It should create `v3.2.2`.

**Pull request merged**
